[project]
name = "turtle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "akshare>=1.17.54",
    "pandas>=2.3.2",
    "pandas-ta>=0.4.71b0",
    "ta-lib>=0.6.7",
]
